---
pool: default
trigger: none
pr:
    - master
steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'JtProject/pom.xml'
        goals: clean package  
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
      displayName: 'Maven Compile'
    - task: CopyFiles@2
      inputs:
        Contents: '**/JtSpringProject*.jar'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: $(Build.Repository.name)